# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mfvb <- function(response, fir_l, sec_l, a_tau, b_tau, a_pi, b_pi, max_iter, max_tol) {
    .Call(`_GraphR_mfvb`, response, fir_l, sec_l, a_tau, b_tau, a_pi, b_pi, max_iter, max_tol)
}

rcpp_hello_world <- function() {
    .Call(`_GraphR_rcpp_hello_world`)
}

